#############################################################################
# Makefile for building: bin/valkyrie
# Generated by qmake (1.07a) (Qt 3.3.1) on: Tue Jul  5 17:15:28 2005
# Project:  valkyrie.pro
# Template: app
# Command: $(QMAKE) -spec /usr/lib/qt3/mkspecs/linux-g++ -o Makefile valkyrie.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -O2 -march=i586 -mcpu=i686 -fmessage-length=0 -Wall -fPIC -O0 -g -Wundef -Wredundant-decls -Wno-unreachable-code -Werror -fno-inline -Wall -W -g -D_REENTRANT  -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -O2 -march=i586 -mcpu=i686 -fmessage-length=0 -Wall -fPIC -O0 -g -Wundef -Wredundant-decls -Wno-unreachable-code -Werror -fno-inline -Wall -W -g -D_REENTRANT  -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt3/mkspecs/linux-g++ -I. -I/usr/include/mysql -Isrc -Isrc/help -Isrc/core -Isrc/options -Isrc/tool_views -Iicons -Isrc/tool_utils -I/usr/include -I/usr/lib/qt3/include -I/usr/X11R6/include -I.moc/
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/lib -L/usr/lib/ -L/usr/lib/qt3/lib -L/usr/X11R6/lib/ -lmysqlclient -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/lib/qt3/bin/moc
UIC      = /usr/lib/qt3/bin/uic -L /usr/lib/qt3/plugins
QMAKE    = /usr/lib/qt3/bin/qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = .obj/

####### Files

HEADERS = src/main_window.h \
		src/vk_config.h \
		src/vk_file_dialog.h \
		src/vk_include.h \
		src/vk_utils.h \
		src/workspace.h \
		icons/filedlg_icons.h \
		icons/msgbox_icons.h \
		icons/tb_handbook_icons.h \
		icons/tb_mainwin_icons.h \
		icons/tb_memcheck_icons.h \
		src/core/cachegrind_object.h \
		src/core/massif_object.h \
		src/core/memcheck_object.h \
		src/core/valgrind_object.h \
		src/core/valkyrie_object.h \
		src/core/vk_objects.h \
		src/help/context_help.h \
		src/help/hand_book.h \
		src/help/help_about.h \
		src/help/html_urls.h \
		src/help/vk_messages.h \
		src/options/cachegrind_options_page.h \
		src/options/intspinbox.h \
		src/options/massif_options_page.h \
		src/options/memcheck_options_page.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/options_window.h \
		src/options/valgrind_options_page.h \
		src/options/valkyrie_options_page.h \
		src/options/vk_option.h \
		src/options/vk_popt.h \
		src/options/vk_popt_option.h \
		src/tool_utils/async_process.h \
		src/tool_utils/logfile.h \
		src/tool_utils/xml_parser.h \
		src/tool_views/cachegrind_view.h \
		src/tool_views/massif_view.h \
		src/tool_views/memcheck_view.h \
		src/tool_views/tool_view.h
SOURCES = src/main.cpp \
		src/main_window.cpp \
		src/vk_config.cpp \
		src/vk_file_dialog.cpp \
		src/vk_utils.cpp \
		src/workspace.cpp \
		src/core/cachegrind_object.cpp \
		src/core/massif_object.cpp \
		src/core/memcheck_object.cpp \
		src/core/valgrind_object.cpp \
		src/core/valkyrie_object.cpp \
		src/core/vk_objects.cpp \
		src/help/context_help.cpp \
		src/help/hand_book.cpp \
		src/help/help_about.cpp \
		src/help/html_urls.cpp \
		src/help/vk_messages.cpp \
		src/options/cachegrind_options_page.cpp \
		src/options/intspinbox.cpp \
		src/options/massif_options_page.cpp \
		src/options/memcheck_options_page.cpp \
		src/options/options_page.cpp \
		src/options/options_widgets.cpp \
		src/options/options_window.cpp \
		src/options/parse_cmd_args.cpp \
		src/options/valgrind_options_page.cpp \
		src/options/valkyrie_options_page.cpp \
		src/options/vk_option.cpp \
		src/options/vk_popt.c \
		src/tool_utils/async_process.cpp \
		src/tool_utils/logfile.cpp \
		src/tool_utils/xml_parser.cpp \
		src/tool_views/cachegrind_view.cpp \
		src/tool_views/massif_view.cpp \
		src/tool_views/memcheck_view.cpp \
		src/tool_views/tool_view.cpp
OBJECTS = .obj/main.o \
		.obj/main_window.o \
		.obj/vk_config.o \
		.obj/vk_file_dialog.o \
		.obj/vk_utils.o \
		.obj/workspace.o \
		.obj/cachegrind_object.o \
		.obj/massif_object.o \
		.obj/memcheck_object.o \
		.obj/valgrind_object.o \
		.obj/valkyrie_object.o \
		.obj/vk_objects.o \
		.obj/context_help.o \
		.obj/hand_book.o \
		.obj/help_about.o \
		.obj/html_urls.o \
		.obj/vk_messages.o \
		.obj/cachegrind_options_page.o \
		.obj/intspinbox.o \
		.obj/massif_options_page.o \
		.obj/memcheck_options_page.o \
		.obj/options_page.o \
		.obj/options_widgets.o \
		.obj/options_window.o \
		.obj/parse_cmd_args.o \
		.obj/valgrind_options_page.o \
		.obj/valkyrie_options_page.o \
		.obj/vk_option.o \
		.obj/vk_popt.o \
		.obj/async_process.o \
		.obj/logfile.o \
		.obj/xml_parser.o \
		.obj/cachegrind_view.o \
		.obj/massif_view.o \
		.obj/memcheck_view.o \
		.obj/tool_view.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = .moc/moc_main_window.cpp \
		.moc/moc_vk_file_dialog.cpp \
		.moc/moc_workspace.cpp \
		.moc/moc_memcheck_object.cpp \
		.moc/moc_valkyrie_object.cpp \
		.moc/moc_vk_objects.cpp \
		.moc/moc_context_help.cpp \
		.moc/moc_hand_book.cpp \
		.moc/moc_help_about.cpp \
		.moc/moc_vk_messages.cpp \
		.moc/moc_cachegrind_options_page.cpp \
		.moc/moc_intspinbox.cpp \
		.moc/moc_massif_options_page.cpp \
		.moc/moc_memcheck_options_page.cpp \
		.moc/moc_options_page.cpp \
		.moc/moc_options_widgets.cpp \
		.moc/moc_options_window.cpp \
		.moc/moc_valgrind_options_page.cpp \
		.moc/moc_valkyrie_options_page.cpp \
		.moc/moc_logfile.cpp \
		.moc/moc_xml_parser.cpp \
		.moc/moc_cachegrind_view.cpp \
		.moc/moc_massif_view.cpp \
		.moc/moc_memcheck_view.cpp \
		.moc/moc_tool_view.cpp \
		.moc/vk_file_dialog.moc
OBJMOC = .obj/moc_main_window.o \
		.obj/moc_vk_file_dialog.o \
		.obj/moc_workspace.o \
		.obj/moc_memcheck_object.o \
		.obj/moc_valkyrie_object.o \
		.obj/moc_vk_objects.o \
		.obj/moc_context_help.o \
		.obj/moc_hand_book.o \
		.obj/moc_help_about.o \
		.obj/moc_vk_messages.o \
		.obj/moc_cachegrind_options_page.o \
		.obj/moc_intspinbox.o \
		.obj/moc_massif_options_page.o \
		.obj/moc_memcheck_options_page.o \
		.obj/moc_options_page.o \
		.obj/moc_options_widgets.o \
		.obj/moc_options_window.o \
		.obj/moc_valgrind_options_page.o \
		.obj/moc_valkyrie_options_page.o \
		.obj/moc_logfile.o \
		.obj/moc_xml_parser.o \
		.obj/moc_cachegrind_view.o \
		.obj/moc_massif_view.o \
		.obj/moc_memcheck_view.o \
		.obj/moc_tool_view.o
DIST	   = valkyrie.pro
QMAKE_TARGET = valkyrie
DESTDIR  = bin/
TARGET   = bin/valkyrie

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: valkyrie.pro  /usr/lib/qt3/mkspecs/linux-g++/qmake.conf 
	$(QMAKE) -spec /usr/lib/qt3/mkspecs/linux-g++ -o Makefile valkyrie.pro
qmake: 
	@$(QMAKE) -spec /usr/lib/qt3/mkspecs/linux-g++ -o Makefile valkyrie.pro

dist: 
	@mkdir -p .obj/valkyrie && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .obj/valkyrie/ && ( cd `dirname .obj/valkyrie` && $(TAR) valkyrie.tar valkyrie && $(GZIP) valkyrie.tar ) && $(MOVE) `dirname .obj/valkyrie`/valkyrie.tar.gz . && $(DEL_FILE) -r .obj/valkyrie

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) bin/$(TARGET) $(TARGET)


FORCE:

####### Compile

.obj/main.o: src/main.cpp src/vk_utils.h \
		src/vk_config.h \
		src/help/vk_messages.h \
		src/main_window.h \
		src/core/vk_objects.h \
		src/core/valkyrie_object.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/workspace.h \
		src/help/help_about.h \
		src/help/hand_book.h \
		src/options/options_window.h \
		src/tool_views/tool_view.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cpp

.obj/main_window.o: src/main_window.cpp src/main_window.h \
		icons/tb_mainwin_icons.h \
		src/vk_config.h \
		src/vk_utils.h \
		src/help/vk_messages.h \
		src/help/context_help.h \
		src/help/html_urls.h \
		src/workspace.h \
		src/help/help_about.h \
		src/help/hand_book.h \
		src/options/options_window.h \
		src/core/vk_objects.h \
		src/core/valkyrie_object.h \
		src/tool_views/tool_view.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main_window.o src/main_window.cpp

.obj/vk_config.o: src/vk_config.cpp src/vk_config.h \
		src/vk_include.h \
		src/vk_utils.h \
		src/help/vk_messages.h \
		src/core/valkyrie_object.h \
		src/core/valgrind_object.h \
		src/core/memcheck_object.h \
		src/core/cachegrind_object.h \
		src/core/massif_object.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/tool_views/memcheck_view.h \
		src/tool_utils/xml_parser.h \
		src/tool_views/tool_view.h \
		src/tool_views/cachegrind_view.h \
		src/tool_views/massif_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_config.o src/vk_config.cpp

.obj/vk_file_dialog.o: src/vk_file_dialog.cpp src/vk_file_dialog.h \
		icons/filedlg_icons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_file_dialog.o src/vk_file_dialog.cpp

.obj/vk_utils.o: src/vk_utils.cpp src/vk_utils.h \
		src/vk_config.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_utils.o src/vk_utils.cpp

.obj/workspace.o: src/workspace.cpp src/workspace.h \
		src/tool_views/tool_view.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/workspace.o src/workspace.cpp

.obj/cachegrind_object.o: src/core/cachegrind_object.cpp src/core/cachegrind_object.h \
		src/vk_config.h \
		src/vk_utils.h \
		src/help/html_urls.h \
		src/help/vk_messages.h \
		src/core/vk_objects.h \
		src/tool_views/cachegrind_view.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/tool_views/tool_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cachegrind_object.o src/core/cachegrind_object.cpp

.obj/massif_object.o: src/core/massif_object.cpp src/core/massif_object.h \
		src/vk_config.h \
		src/vk_utils.h \
		src/help/html_urls.h \
		src/help/vk_messages.h \
		src/core/vk_objects.h \
		src/tool_views/massif_view.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/tool_views/tool_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/massif_object.o src/core/massif_object.cpp

.obj/memcheck_object.o: src/core/memcheck_object.cpp src/core/memcheck_object.h \
		src/vk_config.h \
		src/help/html_urls.h \
		src/help/vk_messages.h \
		src/tool_utils/logfile.h \
		src/core/vk_objects.h \
		src/core/valkyrie_object.h \
		src/tool_views/memcheck_view.h \
		src/tool_utils/xml_parser.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h \
		src/tool_views/tool_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/memcheck_object.o src/core/memcheck_object.cpp

.obj/valgrind_object.o: src/core/valgrind_object.cpp src/core/valgrind_object.h \
		src/vk_config.h \
		src/help/html_urls.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/valgrind_object.o src/core/valgrind_object.cpp

.obj/valkyrie_object.o: src/core/valkyrie_object.cpp src/core/valkyrie_object.h \
		src/core/valgrind_object.h \
		src/core/memcheck_object.h \
		src/core/cachegrind_object.h \
		src/core/massif_object.h \
		src/vk_config.h \
		src/help/vk_messages.h \
		src/vk_utils.h \
		src/help/html_urls.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/tool_views/memcheck_view.h \
		src/tool_utils/xml_parser.h \
		src/tool_views/tool_view.h \
		src/tool_views/cachegrind_view.h \
		src/tool_views/massif_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/valkyrie_object.o src/core/valkyrie_object.cpp

.obj/vk_objects.o: src/core/vk_objects.cpp src/core/vk_objects.h \
		src/vk_config.h \
		src/options/vk_popt_option.h \
		src/help/vk_messages.h \
		src/help/html_urls.h \
		src/core/valkyrie_object.h \
		src/core/valgrind_object.h \
		src/core/memcheck_object.h \
		src/core/cachegrind_object.h \
		src/core/massif_object.h \
		src/options/vk_option.h \
		src/vk_utils.h \
		src/tool_views/memcheck_view.h \
		src/tool_utils/xml_parser.h \
		src/tool_views/tool_view.h \
		src/tool_views/cachegrind_view.h \
		src/tool_views/massif_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_objects.o src/core/vk_objects.cpp

.obj/context_help.o: src/help/context_help.cpp src/help/context_help.h \
		src/help/hand_book.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/context_help.o src/help/context_help.cpp

.obj/hand_book.o: src/help/hand_book.cpp src/help/hand_book.h \
		icons/tb_handbook_icons.h \
		src/vk_config.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/hand_book.o src/help/hand_book.cpp

.obj/help_about.o: src/help/help_about.cpp src/help/help_about.h \
		src/vk_config.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/help_about.o src/help/help_about.cpp

.obj/html_urls.o: src/help/html_urls.cpp src/help/html_urls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/html_urls.o src/help/html_urls.cpp

.obj/vk_messages.o: src/help/vk_messages.cpp src/help/vk_messages.h \
		src/vk_config.h \
		icons/msgbox_icons.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_messages.o src/help/vk_messages.cpp

.obj/cachegrind_options_page.o: src/options/cachegrind_options_page.cpp src/options/cachegrind_options_page.h \
		src/core/cachegrind_object.h \
		src/vk_utils.h \
		src/help/vk_messages.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/core/vk_objects.h \
		src/tool_views/cachegrind_view.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/tool_views/tool_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cachegrind_options_page.o src/options/cachegrind_options_page.cpp

.obj/intspinbox.o: src/options/intspinbox.cpp src/options/intspinbox.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/intspinbox.o src/options/intspinbox.cpp

.obj/massif_options_page.o: src/options/massif_options_page.cpp src/options/massif_options_page.h \
		src/core/massif_object.h \
		src/vk_utils.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/core/vk_objects.h \
		src/tool_views/massif_view.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/tool_views/tool_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/massif_options_page.o src/options/massif_options_page.cpp

.obj/memcheck_options_page.o: src/options/memcheck_options_page.cpp src/options/memcheck_options_page.h \
		src/core/memcheck_object.h \
		src/help/vk_messages.h \
		src/vk_utils.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/core/vk_objects.h \
		src/core/valkyrie_object.h \
		src/tool_views/memcheck_view.h \
		src/tool_utils/xml_parser.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/tool_views/tool_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/memcheck_options_page.o src/options/memcheck_options_page.cpp

.obj/options_page.o: src/options/options_page.cpp src/options/options_page.h \
		src/core/memcheck_object.h \
		src/core/massif_object.h \
		src/vk_utils.h \
		src/vk_config.h \
		src/help/context_help.h \
		src/help/vk_messages.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/core/vk_objects.h \
		src/core/valkyrie_object.h \
		src/tool_views/memcheck_view.h \
		src/tool_utils/xml_parser.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/tool_views/tool_view.h \
		src/tool_views/massif_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/options_page.o src/options/options_page.cpp

.obj/options_widgets.o: src/options/options_widgets.cpp src/options/options_widgets.h \
		src/options/vk_option.h \
		src/vk_utils.h \
		src/vk_config.h \
		src/help/vk_messages.h \
		src/help/context_help.h \
		src/options/vk_popt_option.h \
		src/options/intspinbox.h \
		src/core/vk_objects.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/options_widgets.o src/options/options_widgets.cpp

.obj/options_window.o: src/options/options_window.cpp src/options/options_window.h \
		src/vk_utils.h \
		src/core/vk_objects.h \
		src/vk_config.h \
		src/options/valkyrie_options_page.h \
		src/options/valgrind_options_page.h \
		src/options/memcheck_options_page.h \
		src/options/cachegrind_options_page.h \
		src/options/massif_options_page.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/options_window.o src/options/options_window.cpp

.obj/parse_cmd_args.o: src/options/parse_cmd_args.cpp src/core/vk_objects.h \
		src/core/valkyrie_object.h \
		src/vk_utils.h \
		src/options/vk_popt.h \
		src/vk_config.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/parse_cmd_args.o src/options/parse_cmd_args.cpp

.obj/valgrind_options_page.o: src/options/valgrind_options_page.cpp src/options/valgrind_options_page.h \
		src/core/valgrind_object.h \
		src/vk_config.h \
		src/help/vk_messages.h \
		src/vk_utils.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/valgrind_options_page.o src/options/valgrind_options_page.cpp

.obj/valkyrie_options_page.o: src/options/valkyrie_options_page.cpp src/options/valkyrie_options_page.h \
		src/core/vk_objects.h \
		src/vk_config.h \
		src/vk_utils.h \
		src/main_window.h \
		src/help/vk_messages.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/workspace.h \
		src/help/help_about.h \
		src/help/hand_book.h \
		src/options/options_window.h \
		src/core/valkyrie_object.h \
		src/tool_views/tool_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/valkyrie_options_page.o src/options/valkyrie_options_page.cpp

.obj/vk_option.o: src/options/vk_option.cpp src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_option.o src/options/vk_option.cpp

.obj/vk_popt.o: src/options/vk_popt.c src/options/vk_popt.h \
		src/options/vk_popt_option.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/vk_popt.o src/options/vk_popt.c

.obj/async_process.o: src/tool_utils/async_process.cpp src/tool_utils/async_process.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/async_process.o src/tool_utils/async_process.cpp

.obj/logfile.o: src/tool_utils/logfile.cpp src/tool_utils/logfile.h \
		src/vk_utils.h \
		src/help/vk_messages.h \
		src/tool_utils/xml_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/logfile.o src/tool_utils/logfile.cpp

.obj/xml_parser.o: src/tool_utils/xml_parser.cpp src/tool_utils/xml_parser.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/xml_parser.o src/tool_utils/xml_parser.cpp

.obj/cachegrind_view.o: src/tool_views/cachegrind_view.cpp src/tool_views/cachegrind_view.h \
		src/core/cachegrind_object.h \
		src/tool_views/tool_view.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cachegrind_view.o src/tool_views/cachegrind_view.cpp

.obj/massif_view.o: src/tool_views/massif_view.cpp src/tool_views/massif_view.h \
		src/core/massif_object.h \
		src/tool_views/tool_view.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/massif_view.o src/tool_views/massif_view.cpp

.obj/memcheck_view.o: src/tool_views/memcheck_view.cpp src/tool_views/memcheck_view.h \
		src/core/memcheck_object.h \
		src/vk_config.h \
		icons/tb_memcheck_icons.h \
		src/tool_utils/async_process.h \
		src/help/vk_messages.h \
		src/vk_file_dialog.h \
		src/help/context_help.h \
		src/help/html_urls.h \
		src/tool_views/tool_view.h \
		src/tool_utils/xml_parser.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h \
		src/core/valkyrie_object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/memcheck_view.o src/tool_views/memcheck_view.cpp

.obj/tool_view.o: src/tool_views/tool_view.cpp src/tool_views/tool_view.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/tool_view.o src/tool_views/tool_view.cpp

.obj/moc_main_window.o: .moc/moc_main_window.cpp  src/main_window.h src/workspace.h \
		src/help/help_about.h \
		src/help/hand_book.h \
		src/options/options_window.h \
		src/core/vk_objects.h \
		src/core/valkyrie_object.h \
		src/tool_views/tool_view.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_main_window.o .moc/moc_main_window.cpp

.obj/moc_vk_file_dialog.o: .moc/moc_vk_file_dialog.cpp  src/vk_file_dialog.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_vk_file_dialog.o .moc/moc_vk_file_dialog.cpp

.obj/moc_workspace.o: .moc/moc_workspace.cpp  src/workspace.h src/tool_views/tool_view.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_workspace.o .moc/moc_workspace.cpp

.obj/moc_memcheck_object.o: .moc/moc_memcheck_object.cpp  src/core/memcheck_object.h src/core/vk_objects.h \
		src/core/valkyrie_object.h \
		src/tool_views/memcheck_view.h \
		src/tool_utils/xml_parser.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h \
		src/tool_views/tool_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_memcheck_object.o .moc/moc_memcheck_object.cpp

.obj/moc_valkyrie_object.o: .moc/moc_valkyrie_object.cpp  src/core/valkyrie_object.h src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_valkyrie_object.o .moc/moc_valkyrie_object.cpp

.obj/moc_vk_objects.o: .moc/moc_vk_objects.cpp  src/core/vk_objects.h src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_vk_objects.o .moc/moc_vk_objects.cpp

.obj/moc_context_help.o: .moc/moc_context_help.cpp  src/help/context_help.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_context_help.o .moc/moc_context_help.cpp

.obj/moc_hand_book.o: .moc/moc_hand_book.cpp  src/help/hand_book.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_hand_book.o .moc/moc_hand_book.cpp

.obj/moc_help_about.o: .moc/moc_help_about.cpp  src/help/help_about.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_help_about.o .moc/moc_help_about.cpp

.obj/moc_vk_messages.o: .moc/moc_vk_messages.cpp  src/help/vk_messages.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_vk_messages.o .moc/moc_vk_messages.cpp

.obj/moc_cachegrind_options_page.o: .moc/moc_cachegrind_options_page.cpp  src/options/cachegrind_options_page.h src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_cachegrind_options_page.o .moc/moc_cachegrind_options_page.cpp

.obj/moc_intspinbox.o: .moc/moc_intspinbox.cpp  src/options/intspinbox.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_intspinbox.o .moc/moc_intspinbox.cpp

.obj/moc_massif_options_page.o: .moc/moc_massif_options_page.cpp  src/options/massif_options_page.h src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_massif_options_page.o .moc/moc_massif_options_page.cpp

.obj/moc_memcheck_options_page.o: .moc/moc_memcheck_options_page.cpp  src/options/memcheck_options_page.h src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_memcheck_options_page.o .moc/moc_memcheck_options_page.cpp

.obj/moc_options_page.o: .moc/moc_options_page.cpp  src/options/options_page.h src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_options_page.o .moc/moc_options_page.cpp

.obj/moc_options_widgets.o: .moc/moc_options_widgets.cpp  src/options/options_widgets.h src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_options_widgets.o .moc/moc_options_widgets.cpp

.obj/moc_options_window.o: .moc/moc_options_window.cpp  src/options/options_window.h src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_options_window.o .moc/moc_options_window.cpp

.obj/moc_valgrind_options_page.o: .moc/moc_valgrind_options_page.cpp  src/options/valgrind_options_page.h src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_valgrind_options_page.o .moc/moc_valgrind_options_page.cpp

.obj/moc_valkyrie_options_page.o: .moc/moc_valkyrie_options_page.cpp  src/options/valkyrie_options_page.h src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_valkyrie_options_page.o .moc/moc_valkyrie_options_page.cpp

.obj/moc_logfile.o: .moc/moc_logfile.cpp  src/tool_utils/logfile.h src/tool_utils/xml_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_logfile.o .moc/moc_logfile.cpp

.obj/moc_xml_parser.o: .moc/moc_xml_parser.cpp  src/tool_utils/xml_parser.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_xml_parser.o .moc/moc_xml_parser.cpp

.obj/moc_cachegrind_view.o: .moc/moc_cachegrind_view.cpp  src/tool_views/cachegrind_view.h src/tool_views/tool_view.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_cachegrind_view.o .moc/moc_cachegrind_view.cpp

.obj/moc_massif_view.o: .moc/moc_massif_view.cpp  src/tool_views/massif_view.h src/tool_views/tool_view.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_massif_view.o .moc/moc_massif_view.cpp

.obj/moc_memcheck_view.o: .moc/moc_memcheck_view.cpp  src/tool_views/memcheck_view.h src/tool_views/tool_view.h \
		src/tool_utils/xml_parser.h \
		src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_memcheck_view.o .moc/moc_memcheck_view.cpp

.obj/moc_tool_view.o: .moc/moc_tool_view.cpp  src/tool_views/tool_view.h src/core/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_tool_view.o .moc/moc_tool_view.cpp

.moc/moc_main_window.cpp: $(MOC) src/main_window.h
	$(MOC) src/main_window.h -o .moc/moc_main_window.cpp

.moc/moc_vk_file_dialog.cpp: $(MOC) src/vk_file_dialog.h
	$(MOC) src/vk_file_dialog.h -o .moc/moc_vk_file_dialog.cpp

.moc/moc_workspace.cpp: $(MOC) src/workspace.h
	$(MOC) src/workspace.h -o .moc/moc_workspace.cpp

.moc/moc_memcheck_object.cpp: $(MOC) src/core/memcheck_object.h
	$(MOC) src/core/memcheck_object.h -o .moc/moc_memcheck_object.cpp

.moc/moc_valkyrie_object.cpp: $(MOC) src/core/valkyrie_object.h
	$(MOC) src/core/valkyrie_object.h -o .moc/moc_valkyrie_object.cpp

.moc/moc_vk_objects.cpp: $(MOC) src/core/vk_objects.h
	$(MOC) src/core/vk_objects.h -o .moc/moc_vk_objects.cpp

.moc/moc_context_help.cpp: $(MOC) src/help/context_help.h
	$(MOC) src/help/context_help.h -o .moc/moc_context_help.cpp

.moc/moc_hand_book.cpp: $(MOC) src/help/hand_book.h
	$(MOC) src/help/hand_book.h -o .moc/moc_hand_book.cpp

.moc/moc_help_about.cpp: $(MOC) src/help/help_about.h
	$(MOC) src/help/help_about.h -o .moc/moc_help_about.cpp

.moc/moc_vk_messages.cpp: $(MOC) src/help/vk_messages.h
	$(MOC) src/help/vk_messages.h -o .moc/moc_vk_messages.cpp

.moc/moc_cachegrind_options_page.cpp: $(MOC) src/options/cachegrind_options_page.h
	$(MOC) src/options/cachegrind_options_page.h -o .moc/moc_cachegrind_options_page.cpp

.moc/moc_intspinbox.cpp: $(MOC) src/options/intspinbox.h
	$(MOC) src/options/intspinbox.h -o .moc/moc_intspinbox.cpp

.moc/moc_massif_options_page.cpp: $(MOC) src/options/massif_options_page.h
	$(MOC) src/options/massif_options_page.h -o .moc/moc_massif_options_page.cpp

.moc/moc_memcheck_options_page.cpp: $(MOC) src/options/memcheck_options_page.h
	$(MOC) src/options/memcheck_options_page.h -o .moc/moc_memcheck_options_page.cpp

.moc/moc_options_page.cpp: $(MOC) src/options/options_page.h
	$(MOC) src/options/options_page.h -o .moc/moc_options_page.cpp

.moc/moc_options_widgets.cpp: $(MOC) src/options/options_widgets.h
	$(MOC) src/options/options_widgets.h -o .moc/moc_options_widgets.cpp

.moc/moc_options_window.cpp: $(MOC) src/options/options_window.h
	$(MOC) src/options/options_window.h -o .moc/moc_options_window.cpp

.moc/moc_valgrind_options_page.cpp: $(MOC) src/options/valgrind_options_page.h
	$(MOC) src/options/valgrind_options_page.h -o .moc/moc_valgrind_options_page.cpp

.moc/moc_valkyrie_options_page.cpp: $(MOC) src/options/valkyrie_options_page.h
	$(MOC) src/options/valkyrie_options_page.h -o .moc/moc_valkyrie_options_page.cpp

.moc/moc_logfile.cpp: $(MOC) src/tool_utils/logfile.h
	$(MOC) src/tool_utils/logfile.h -o .moc/moc_logfile.cpp

.moc/moc_xml_parser.cpp: $(MOC) src/tool_utils/xml_parser.h
	$(MOC) src/tool_utils/xml_parser.h -o .moc/moc_xml_parser.cpp

.moc/moc_cachegrind_view.cpp: $(MOC) src/tool_views/cachegrind_view.h
	$(MOC) src/tool_views/cachegrind_view.h -o .moc/moc_cachegrind_view.cpp

.moc/moc_massif_view.cpp: $(MOC) src/tool_views/massif_view.h
	$(MOC) src/tool_views/massif_view.h -o .moc/moc_massif_view.cpp

.moc/moc_memcheck_view.cpp: $(MOC) src/tool_views/memcheck_view.h
	$(MOC) src/tool_views/memcheck_view.h -o .moc/moc_memcheck_view.cpp

.moc/moc_tool_view.cpp: $(MOC) src/tool_views/tool_view.h
	$(MOC) src/tool_views/tool_view.h -o .moc/moc_tool_view.cpp

.moc/vk_file_dialog.moc: $(MOC) src/vk_file_dialog.cpp
	$(MOC) src/vk_file_dialog.cpp -o .moc/vk_file_dialog.moc

####### Install

install:  

uninstall:  

