#############################################################################
# Makefile for building: bin/valkyrie
# Generated by qmake (1.07a) (Qt 3.3.1) on: Tue Jun 14 14:28:37 2005
# Project:  valkyrie.pro
# Template: app
# Command: $(QMAKE) -o Makefile valkyrie.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -O2 -march=i586 -mcpu=i686 -fmessage-length=0 -Wall -fPIC -Wall -W -O0 -g -Wundef -Wredundant-decls -Wunreachable-code -fno-inline -D_REENTRANT  -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -O2 -march=i586 -mcpu=i686 -fmessage-length=0 -Wall -fPIC -Wall -W -O0 -g -Wundef -Wredundant-decls -Wunreachable-code -fno-inline -D_REENTRANT  -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt3/mkspecs/default -I. -Isrc -Isrc/options -Isrc/help -Iicons -Isrc/memcheck -Isrc/cachegrind -Isrc/massif -I/usr/include -I$(QTDIR)/include -I/usr/X11R6/include -I.moc/
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/lib/ -L$(QTDIR)/lib/ -L/usr/X11R6/lib/ -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = .obj/

####### Files

HEADERS = src/async_process.h \
		src/main_window.h \
		src/tool_view.h \
		src/vk_config.h \
		src/vk_include.h \
		src/vk_msgbox.h \
		src/vk_utils.h \
		src/workspace.h \
		icons/msgbox_icons.h \
		icons/tb_handbook_icons.h \
		icons/tb_mainwin_icons.h \
		icons/tb_memcheck_icons.h \
		src/cachegrind/cachegrind_view.h \
		src/help/context_help.h \
		src/help/hand_book.h \
		src/help/help_info.h \
		src/help/html_urls.h \
		src/massif/massif_view.h \
		src/memcheck/memcheck_view.h \
		src/memcheck/xml_parser.h \
		src/options/intspinbox.h \
		src/options/massif_options_page.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/options_window.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt.h \
		src/options/vk_popt_option.h
SOURCES = src/async_process.cpp \
		src/main.cpp \
		src/main_window.cpp \
		src/tool_view.cpp \
		src/vk_config.cpp \
		src/vk_msgbox.cpp \
		src/vk_utils.cpp \
		src/workspace.cpp \
		src/cachegrind/cachegrind_view.cpp \
		src/help/context_help.cpp \
		src/help/hand_book.cpp \
		src/help/help_info.cpp \
		src/help/html_urls.cpp \
		src/massif/massif_view.cpp \
		src/memcheck/memcheck_view.cpp \
		src/memcheck/xml_parser.cpp \
		src/options/intspinbox.cpp \
		src/options/massif_options_page.cpp \
		src/options/options_page.cpp \
		src/options/options_widgets.cpp \
		src/options/options_window.cpp \
		src/options/parse_cmd_args.cpp \
		src/options/vk_objects.cpp \
		src/options/vk_option.cpp \
		src/options/vk_popt.c
OBJECTS = .obj/async_process.o \
		.obj/main.o \
		.obj/main_window.o \
		.obj/tool_view.o \
		.obj/vk_config.o \
		.obj/vk_msgbox.o \
		.obj/vk_utils.o \
		.obj/workspace.o \
		.obj/cachegrind_view.o \
		.obj/context_help.o \
		.obj/hand_book.o \
		.obj/help_info.o \
		.obj/html_urls.o \
		.obj/massif_view.o \
		.obj/memcheck_view.o \
		.obj/xml_parser.o \
		.obj/intspinbox.o \
		.obj/massif_options_page.o \
		.obj/options_page.o \
		.obj/options_widgets.o \
		.obj/options_window.o \
		.obj/parse_cmd_args.o \
		.obj/vk_objects.o \
		.obj/vk_option.o \
		.obj/vk_popt.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = .moc/moc_main_window.cpp \
		.moc/moc_tool_view.cpp \
		.moc/moc_vk_msgbox.cpp \
		.moc/moc_workspace.cpp \
		.moc/moc_cachegrind_view.cpp \
		.moc/moc_context_help.cpp \
		.moc/moc_hand_book.cpp \
		.moc/moc_help_info.cpp \
		.moc/moc_massif_view.cpp \
		.moc/moc_memcheck_view.cpp \
		.moc/moc_intspinbox.cpp \
		.moc/moc_massif_options_page.cpp \
		.moc/moc_options_page.cpp \
		.moc/moc_options_widgets.cpp \
		.moc/moc_options_window.cpp
OBJMOC = .obj/moc_main_window.o \
		.obj/moc_tool_view.o \
		.obj/moc_vk_msgbox.o \
		.obj/moc_workspace.o \
		.obj/moc_cachegrind_view.o \
		.obj/moc_context_help.o \
		.obj/moc_hand_book.o \
		.obj/moc_help_info.o \
		.obj/moc_massif_view.o \
		.obj/moc_memcheck_view.o \
		.obj/moc_intspinbox.o \
		.obj/moc_massif_options_page.o \
		.obj/moc_options_page.o \
		.obj/moc_options_widgets.o \
		.obj/moc_options_window.o
DIST	   = valkyrie.sources \
		valkyrie.pro
QMAKE_TARGET = valkyrie
DESTDIR  = bin/
TARGET   = bin/valkyrie

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: valkyrie.pro  /usr/lib/qt3/mkspecs/default/qmake.conf valkyrie.sources
	$(QMAKE) -o Makefile valkyrie.pro
qmake: 
	@$(QMAKE) -o Makefile valkyrie.pro

dist: 
	@mkdir -p .obj/valkyrie && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .obj/valkyrie/ && ( cd `dirname .obj/valkyrie` && $(TAR) valkyrie.tar valkyrie && $(GZIP) valkyrie.tar ) && $(MOVE) `dirname .obj/valkyrie`/valkyrie.tar.gz . && $(DEL_FILE) -r .obj/valkyrie

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) bin/$(TARGET) $(TARGET)


FORCE:

####### Compile

.obj/async_process.o: src/async_process.cpp src/async_process.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/async_process.o src/async_process.cpp

.obj/main.o: src/main.cpp src/vk_include.h \
		src/vk_utils.h \
		src/vk_config.h \
		src/vk_msgbox.h \
		src/options/vk_objects.h \
		src/main_window.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/workspace.h \
		src/help/help_info.h \
		src/help/hand_book.h \
		src/options/options_window.h \
		src/tool_view.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cpp

.obj/main_window.o: src/main_window.cpp src/main_window.h \
		icons/tb_mainwin_icons.h \
		src/vk_include.h \
		src/vk_config.h \
		src/vk_utils.h \
		src/vk_msgbox.h \
		src/help/context_help.h \
		src/help/html_urls.h \
		src/memcheck/memcheck_view.h \
		src/cachegrind/cachegrind_view.h \
		src/massif/massif_view.h \
		src/workspace.h \
		src/help/help_info.h \
		src/help/hand_book.h \
		src/options/options_window.h \
		src/tool_view.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/memcheck/xml_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main_window.o src/main_window.cpp

.obj/tool_view.o: src/tool_view.cpp src/tool_view.h \
		src/vk_include.h \
		src/vk_config.h \
		src/vk_msgbox.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/tool_view.o src/tool_view.cpp

.obj/vk_config.o: src/vk_config.cpp src/vk_config.h \
		src/vk_include.h \
		src/vk_utils.h \
		src/vk_msgbox.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_config.o src/vk_config.cpp

.obj/vk_msgbox.o: src/vk_msgbox.cpp src/vk_msgbox.h \
		src/vk_include.h \
		src/vk_config.h \
		icons/msgbox_icons.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_msgbox.o src/vk_msgbox.cpp

.obj/vk_utils.o: src/vk_utils.cpp src/vk_utils.h \
		src/vk_include.h \
		src/vk_config.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_utils.o src/vk_utils.cpp

.obj/workspace.o: src/workspace.cpp src/workspace.h \
		src/tool_view.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/workspace.o src/workspace.cpp

.obj/cachegrind_view.o: src/cachegrind/cachegrind_view.cpp src/cachegrind/cachegrind_view.h \
		src/tool_view.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cachegrind_view.o src/cachegrind/cachegrind_view.cpp

.obj/context_help.o: src/help/context_help.cpp src/help/context_help.h \
		src/help/hand_book.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/context_help.o src/help/context_help.cpp

.obj/hand_book.o: src/help/hand_book.cpp src/help/hand_book.h \
		icons/tb_handbook_icons.h \
		src/vk_include.h \
		src/vk_config.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/hand_book.o src/help/hand_book.cpp

.obj/help_info.o: src/help/help_info.cpp src/help/help_info.h \
		src/vk_include.h \
		src/vk_config.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/help_info.o src/help/help_info.cpp

.obj/html_urls.o: src/help/html_urls.cpp src/help/html_urls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/html_urls.o src/help/html_urls.cpp

.obj/massif_view.o: src/massif/massif_view.cpp src/massif/massif_view.h \
		src/tool_view.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/massif_view.o src/massif/massif_view.cpp

.obj/memcheck_view.o: src/memcheck/memcheck_view.cpp src/memcheck/memcheck_view.h \
		src/vk_include.h \
		src/vk_config.h \
		icons/tb_memcheck_icons.h \
		src/vk_utils.h \
		src/async_process.h \
		src/vk_msgbox.h \
		src/tool_view.h \
		src/memcheck/xml_parser.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/memcheck_view.o src/memcheck/memcheck_view.cpp

.obj/xml_parser.o: src/memcheck/xml_parser.cpp src/memcheck/xml_parser.h \
		src/memcheck/memcheck_view.h \
		src/vk_utils.h \
		src/tool_view.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/xml_parser.o src/memcheck/xml_parser.cpp

.obj/intspinbox.o: src/options/intspinbox.cpp src/options/intspinbox.h \
		src/vk_include.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/intspinbox.o src/options/intspinbox.cpp

.obj/massif_options_page.o: src/options/massif_options_page.cpp src/options/massif_options_page.h \
		src/options/vk_objects.h \
		src/vk_utils.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/massif_options_page.o src/options/massif_options_page.cpp

.obj/options_page.o: src/options/options_page.cpp src/options/options_page.h \
		src/vk_include.h \
		src/options/vk_objects.h \
		src/vk_utils.h \
		src/vk_config.h \
		src/help/context_help.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/options_page.o src/options/options_page.cpp

.obj/options_widgets.o: src/options/options_widgets.cpp src/options/options_widgets.h \
		src/options/vk_option.h \
		src/vk_include.h \
		src/vk_utils.h \
		src/vk_config.h \
		src/vk_msgbox.h \
		src/options/intspinbox.h \
		src/options/vk_objects.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/options_widgets.o src/options/options_widgets.cpp

.obj/options_window.o: src/options/options_window.cpp src/options/options_window.h \
		src/vk_include.h \
		src/vk_utils.h \
		src/options/vk_objects.h \
		src/vk_config.h \
		src/options/massif_options_page.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/options_window.o src/options/options_window.cpp

.obj/parse_cmd_args.o: src/options/parse_cmd_args.cpp src/options/vk_objects.h \
		src/vk_include.h \
		src/vk_utils.h \
		src/options/vk_popt.h \
		src/vk_config.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/parse_cmd_args.o src/options/parse_cmd_args.cpp

.obj/vk_objects.o: src/options/vk_objects.cpp src/options/vk_objects.h \
		src/vk_include.h \
		src/vk_config.h \
		src/vk_utils.h \
		src/options/vk_popt_option.h \
		src/vk_msgbox.h \
		src/help/html_urls.h \
		src/options/vk_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_objects.o src/options/vk_objects.cpp

.obj/vk_option.o: src/options/vk_option.cpp src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/vk_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vk_option.o src/options/vk_option.cpp

.obj/vk_popt.o: src/options/vk_popt.c src/options/vk_popt.h \
		src/options/vk_popt_option.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/vk_popt.o src/options/vk_popt.c

.obj/moc_main_window.o: .moc/moc_main_window.cpp  src/main_window.h src/workspace.h \
		src/help/help_info.h \
		src/help/hand_book.h \
		src/options/options_window.h \
		src/tool_view.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h \
		src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_main_window.o .moc/moc_main_window.cpp

.obj/moc_tool_view.o: .moc/moc_tool_view.cpp  src/tool_view.h src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_tool_view.o .moc/moc_tool_view.cpp

.obj/moc_vk_msgbox.o: .moc/moc_vk_msgbox.cpp  src/vk_msgbox.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_vk_msgbox.o .moc/moc_vk_msgbox.cpp

.obj/moc_workspace.o: .moc/moc_workspace.cpp  src/workspace.h src/tool_view.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_workspace.o .moc/moc_workspace.cpp

.obj/moc_cachegrind_view.o: .moc/moc_cachegrind_view.cpp  src/cachegrind/cachegrind_view.h src/tool_view.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_cachegrind_view.o .moc/moc_cachegrind_view.cpp

.obj/moc_context_help.o: .moc/moc_context_help.cpp  src/help/context_help.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_context_help.o .moc/moc_context_help.cpp

.obj/moc_hand_book.o: .moc/moc_hand_book.cpp  src/help/hand_book.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_hand_book.o .moc/moc_hand_book.cpp

.obj/moc_help_info.o: .moc/moc_help_info.cpp  src/help/help_info.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_help_info.o .moc/moc_help_info.cpp

.obj/moc_massif_view.o: .moc/moc_massif_view.cpp  src/massif/massif_view.h src/tool_view.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_massif_view.o .moc/moc_massif_view.cpp

.obj/moc_memcheck_view.o: .moc/moc_memcheck_view.cpp  src/memcheck/memcheck_view.h src/tool_view.h \
		src/memcheck/xml_parser.h \
		src/options/vk_objects.h \
		src/options/vk_option.h \
		src/options/vk_popt_option.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_memcheck_view.o .moc/moc_memcheck_view.cpp

.obj/moc_intspinbox.o: .moc/moc_intspinbox.cpp  src/options/intspinbox.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_intspinbox.o .moc/moc_intspinbox.cpp

.obj/moc_massif_options_page.o: .moc/moc_massif_options_page.cpp  src/options/massif_options_page.h src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_massif_options_page.o .moc/moc_massif_options_page.cpp

.obj/moc_options_page.o: .moc/moc_options_page.cpp  src/options/options_page.h src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_options_page.o .moc/moc_options_page.cpp

.obj/moc_options_widgets.o: .moc/moc_options_widgets.cpp  src/options/options_widgets.h src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_options_widgets.o .moc/moc_options_widgets.cpp

.obj/moc_options_window.o: .moc/moc_options_window.cpp  src/options/options_window.h src/options/options_page.h \
		src/options/options_widgets.h \
		src/options/intspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_options_window.o .moc/moc_options_window.cpp

.moc/moc_main_window.cpp: $(MOC) src/main_window.h
	$(MOC) src/main_window.h -o .moc/moc_main_window.cpp

.moc/moc_tool_view.cpp: $(MOC) src/tool_view.h
	$(MOC) src/tool_view.h -o .moc/moc_tool_view.cpp

.moc/moc_vk_msgbox.cpp: $(MOC) src/vk_msgbox.h
	$(MOC) src/vk_msgbox.h -o .moc/moc_vk_msgbox.cpp

.moc/moc_workspace.cpp: $(MOC) src/workspace.h
	$(MOC) src/workspace.h -o .moc/moc_workspace.cpp

.moc/moc_cachegrind_view.cpp: $(MOC) src/cachegrind/cachegrind_view.h
	$(MOC) src/cachegrind/cachegrind_view.h -o .moc/moc_cachegrind_view.cpp

.moc/moc_context_help.cpp: $(MOC) src/help/context_help.h
	$(MOC) src/help/context_help.h -o .moc/moc_context_help.cpp

.moc/moc_hand_book.cpp: $(MOC) src/help/hand_book.h
	$(MOC) src/help/hand_book.h -o .moc/moc_hand_book.cpp

.moc/moc_help_info.cpp: $(MOC) src/help/help_info.h
	$(MOC) src/help/help_info.h -o .moc/moc_help_info.cpp

.moc/moc_massif_view.cpp: $(MOC) src/massif/massif_view.h
	$(MOC) src/massif/massif_view.h -o .moc/moc_massif_view.cpp

.moc/moc_memcheck_view.cpp: $(MOC) src/memcheck/memcheck_view.h
	$(MOC) src/memcheck/memcheck_view.h -o .moc/moc_memcheck_view.cpp

.moc/moc_intspinbox.cpp: $(MOC) src/options/intspinbox.h
	$(MOC) src/options/intspinbox.h -o .moc/moc_intspinbox.cpp

.moc/moc_massif_options_page.cpp: $(MOC) src/options/massif_options_page.h
	$(MOC) src/options/massif_options_page.h -o .moc/moc_massif_options_page.cpp

.moc/moc_options_page.cpp: $(MOC) src/options/options_page.h
	$(MOC) src/options/options_page.h -o .moc/moc_options_page.cpp

.moc/moc_options_widgets.cpp: $(MOC) src/options/options_widgets.h
	$(MOC) src/options/options_widgets.h -o .moc/moc_options_widgets.cpp

.moc/moc_options_window.cpp: $(MOC) src/options/options_window.h
	$(MOC) src/options/options_window.h -o .moc/moc_options_window.cpp

####### Install

install:  

uninstall:  

